language: node_js
node_js:
  - "12.13.0"
# cache:
#  directories:
#  - node_modules
before_script:
  - "npm i -g gatsby"
  - "npm i"
  - "npm build"
script:
  - "npm run test"
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
