language: node_js
node_js:
  - "stable"
# cache:
#  directories:
#  - node_modules
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
